### ISSUE TITLE
Any plans to release?

### ISSUE THREAD

**Issue by SCUTykLin** [umarkhalidAI/LatentEditor#1]
Any plans to release? Thanks

**Comment by hasan1292** [comment]
Hi, thank you for showing interest in our project! We will release the code soon!

**Comment by khushalrs** [comment]
Hey, I am also looking forward to try your project. Tentatively, by when are you releasing the code?

**Comment by umarkhalidAI** [comment]
> Hey, I am also looking forward to try your project. Tentatively, by when are you releasing the code?

We are waiting for the paper acceptance. We have intentionally left certain details missing in the Arxiv version and will release the code as the paper gets accpeted.
